// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartNeighborhoodAPI;

#nullable disable

namespace SmartNeighborhoodAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260112110332_seeddataforfamilies")]
    partial class seeddataforfamilies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdGroup", b =>
                {
                    b.Property<int>("AdsId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsId")
                        .HasColumnType("int");

                    b.HasKey("AdsId", "GroupsId");

                    b.HasIndex("GroupsId");

                    b.ToTable("AdGroup");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Name = "BlockManager",
                            NormalizedName = "BLOCKMANAGER"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            Name = "UnitManager",
                            NormalizedName = "UNITMANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            RoleId = "11111111-1111-1111-1111-111111111111"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdsText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentialUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockManagerId")
                        .IsUnique();

                    b.HasIndex("ResidentialUnitId");

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockManagerId = "dddddddd-dddd-dddd-dddd-dddddddddddd",
                            Name = "المربع الأول",
                            ResidentialUnitId = 1
                        },
                        new
                        {
                            Id = 2,
                            BlockManagerId = "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                            Name = "المربع الثاني",
                            ResidentialUnitId = 1
                        },
                        new
                        {
                            Id = 3,
                            BlockManagerId = "ffffffff-ffff-ffff-ffff-ffffffffffff",
                            Name = "المربع الثالث",
                            ResidentialUnitId = 1
                        },
                        new
                        {
                            Id = 4,
                            BlockManagerId = "10101010-1010-1010-1010-101010101010",
                            Name = "المربع الرابع",
                            ResidentialUnitId = 1
                        },
                        new
                        {
                            Id = 5,
                            BlockManagerId = "20202020-2020-2020-2020-202020202020",
                            Name = "المربع الخامس",
                            ResidentialUnitId = 1
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ConfilctType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfilctTypes");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ConflictCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("ConflictTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FirstPartyId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecondPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("ConflictTypeId");

                    b.HasIndex("FirstPartyId");

                    b.HasIndex("SecondPartyId");

                    b.ToTable("ConfilctCases");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyCatgoryId")
                        .HasColumnType("int");

                    b.Property<string>("FamilyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HousingType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("FamilyCatgoryId");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlockId = 1,
                            FamilyCatgoryId = 1,
                            FamilyNotes = "عائلة محتاجة للدعم",
                            HousingType = 2,
                            Location = "شارع الملك فهد، حي السلام",
                            Name = "عائلة الأحمدي"
                        },
                        new
                        {
                            Id = 2,
                            BlockId = 1,
                            FamilyCatgoryId = 3,
                            FamilyNotes = "عائلة متوسطة الدخل",
                            HousingType = 1,
                            Location = "شارع العروبة، حي السلام",
                            Name = "عائلة السعيد"
                        },
                        new
                        {
                            Id = 3,
                            BlockId = 2,
                            FamilyCatgoryId = 2,
                            FamilyNotes = "عائلة يتيمة",
                            HousingType = 2,
                            Location = "شارع الأمير سلطان، حي السلام",
                            Name = "عائلة القحطاني"
                        },
                        new
                        {
                            Id = 4,
                            BlockId = 2,
                            FamilyCatgoryId = 3,
                            HousingType = 1,
                            Location = "شارع الملك عبدالعزيز، حي السلام",
                            Name = "عائلة الدوسري"
                        },
                        new
                        {
                            Id = 5,
                            BlockId = 3,
                            FamilyCatgoryId = 1,
                            FamilyNotes = "عائلة كبيرة",
                            HousingType = 2,
                            Location = "شارع الخليج، حي السلام",
                            Name = "عائلة الشمري"
                        },
                        new
                        {
                            Id = 6,
                            BlockId = 3,
                            FamilyCatgoryId = 3,
                            HousingType = 1,
                            Location = "شارع الأمل، حي السلام",
                            Name = "عائلة الغامدي"
                        },
                        new
                        {
                            Id = 7,
                            BlockId = 4,
                            FamilyCatgoryId = 2,
                            FamilyNotes = "عائلة محتاجة",
                            HousingType = 2,
                            Location = "شارع النخيل، حي السلام",
                            Name = "عائلة العمري"
                        },
                        new
                        {
                            Id = 8,
                            BlockId = 4,
                            FamilyCatgoryId = 3,
                            HousingType = 1,
                            Location = "شارع الورود، حي السلام",
                            Name = "عائلة المطيري"
                        },
                        new
                        {
                            Id = 9,
                            BlockId = 5,
                            FamilyCatgoryId = 1,
                            FamilyNotes = "عائلة أرملة",
                            HousingType = 2,
                            Location = "شارع السلام، حي السلام",
                            Name = "عائلة الزهراني"
                        },
                        new
                        {
                            Id = 10,
                            BlockId = 5,
                            FamilyCatgoryId = 3,
                            HousingType = 1,
                            Location = "شارع الفيحاء، حي السلام",
                            Name = "عائلة الحربي"
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.FamilyCatgory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FamilyCatgories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<int>("MemberFamilyRoleId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MemberFamilyRoleId");

                    b.HasIndex("PersonId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.MemberFamilyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MemberFamilyRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "أب"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "أم"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "ابن"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "ابنة"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "جد"
                        },
                        new
                        {
                            Id = 6,
                            RoleName = "جدة"
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasMaxLength(100)
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsContactNumber")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsWhatsapp")
                        .HasColumnType("bit");

                    b.Property<string>("Job")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int>("OccupationStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("personType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodType = 5,
                            FirstName = "أحمد",
                            Gender = 0,
                            Job = "مهندس",
                            LastName = "الزهيري",
                            MaritalStatus = 2,
                            OccupationStatus = 2,
                            PhoneNumber = "0791234567",
                            SecondName = "سعيد",
                            ThirdName = "محمود",
                            personType = 3
                        },
                        new
                        {
                            Id = 2,
                            BloodType = 5,
                            FirstName = "فاطمة",
                            Gender = 1,
                            Job = "طالبة",
                            LastName = "الحسني",
                            MaritalStatus = 1,
                            OccupationStatus = 1,
                            PhoneNumber = "0789876543",
                            SecondName = "خالد",
                            ThirdName = "عبد الله",
                            personType = 0
                        },
                        new
                        {
                            Id = 222,
                            BloodType = 0,
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "أحمد",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "السعيد",
                            MaritalStatus = 2,
                            OccupationStatus = 2,
                            PhoneNumber = "0501234567",
                            SecondName = "محمد",
                            ThirdName = "علي",
                            personType = 0
                        },
                        new
                        {
                            Id = 223,
                            BloodType = 7,
                            DateOfBirth = new DateTime(1988, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "خالد",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "العمري",
                            MaritalStatus = 2,
                            OccupationStatus = 3,
                            PhoneNumber = "0502345678",
                            SecondName = "عبدالله",
                            ThirdName = "محمد",
                            personType = 0
                        },
                        new
                        {
                            Id = 224,
                            BloodType = 2,
                            DateOfBirth = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "محمد",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "الأحمدي",
                            MaritalStatus = 1,
                            OccupationStatus = 1,
                            PhoneNumber = "0503456789",
                            SecondName = "سعيد",
                            ThirdName = "أحمد",
                            personType = 0
                        },
                        new
                        {
                            Id = 225,
                            BloodType = 4,
                            DateOfBirth = new DateTime(1987, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "عبدالرحمن",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "القحطاني",
                            MaritalStatus = 2,
                            OccupationStatus = 3,
                            PhoneNumber = "0504567890",
                            SecondName = "فيصل",
                            ThirdName = "عبدالله",
                            personType = 0
                        },
                        new
                        {
                            Id = 226,
                            BloodType = 0,
                            DateOfBirth = new DateTime(1992, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "سعود",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "الدوسري",
                            MaritalStatus = 1,
                            OccupationStatus = 1,
                            PhoneNumber = "0505678901",
                            SecondName = "يوسف",
                            ThirdName = "علي",
                            personType = 0
                        },
                        new
                        {
                            Id = 227,
                            BloodType = 6,
                            DateOfBirth = new DateTime(1989, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "فهد",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "الشمري",
                            MaritalStatus = 2,
                            OccupationStatus = 3,
                            PhoneNumber = "0506789012",
                            SecondName = "إبراهيم",
                            ThirdName = "محمد",
                            personType = 2
                        },
                        new
                        {
                            Id = 228,
                            BloodType = 2,
                            DateOfBirth = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "ناصر",
                            Gender = 0,
                            IsContactNumber = true,
                            IsWhatsapp = true,
                            LastName = "الغامدي",
                            MaritalStatus = 1,
                            OccupationStatus = 1,
                            PhoneNumber = "0507890123",
                            SecondName = "علي",
                            ThirdName = "سعد",
                            personType = 2
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectCatogoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectPriority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCatogoryId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ProjectCatogory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProjectCatogories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "مشاريع سكنية",
                            Name = "سكني"
                        },
                        new
                        {
                            Id = 2,
                            Description = "مشاريع تجارية",
                            Name = "تجاري"
                        },
                        new
                        {
                            Id = 3,
                            Description = "مشاريع تعليمية",
                            Name = "تعليمي"
                        },
                        new
                        {
                            Id = 4,
                            Description = "مشاريع مساعدات",
                            Name = "مساعدات"
                        });
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ProjectFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyID")
                        .HasColumnType("int");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateReceived")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FamilyID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectFamilies");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TeamRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailConfirmationCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("EmailConfirmationCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21683088-4ec1-4ec5-9ea3-21fb77e7786d",
                            Email = "sys.smartneighborhood@gmail.com",
                            EmailConfirmed = true,
                            IsActive = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "sys.smartneighborhood@gmail.com",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAy3JPVkFDvphF4YwdU9pYTDi1E2syl9obPzwkRsVdsnVAibhynU697BlfEZZRkb/Q==",
                            PersonId = 1,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f79ae376-4d5a-4a85-8130-a3068e995613",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85000fb3-d7d6-47a5-8067-10ef46986a3f",
                            Email = "neighborhood.manager@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "NEIGHBORHOOD.MANAGER@TEST.COM",
                            NormalizedUserName = "NEIGHBORHOODMANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEE1SvnaCaPFZpbQHFu5I6gvtqEvfhK5tDKir14YBqDVh/9Rl2tJ4yGm22rxZIgYqhA==",
                            PersonId = 2,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0599cd83-7915-4434-bdeb-94c196cdd7e8",
                            TwoFactorEnabled = false,
                            UserName = "NeighborhoodManager1"
                        },
                        new
                        {
                            Id = "cccccccc-cccc-cccc-cccc-cccccccccccc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "845c9793-6aa6-4c3d-8905-e965c2198a08",
                            Email = "unit.manager@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "UNIT.MANAGER@TEST.COM",
                            NormalizedUserName = "UNITMANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAELdCOiyVIZttZ4Yl/Ck3fGrwgE9b/KSvdnFvIVfy0C+uZ980/5YCGb/GFZEnzZswgg==",
                            PersonId = 3,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f42c013-d1c5-429b-8307-4899707e9b89",
                            TwoFactorEnabled = false,
                            UserName = "UnitManager1"
                        },
                        new
                        {
                            Id = "dddddddd-dddd-dddd-dddd-dddddddddddd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a6e8858-48f1-4e11-a1cf-8f59a3e96e41",
                            Email = "block.manager1@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BLOCK.MANAGER1@TEST.COM",
                            NormalizedUserName = "BLOCKMANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEBqG5JV2uaapkcXYtRZXgHBb+fRCG9va4IweC2x/30pa1ZQsvqtf1sgOOCJHVFahhQ==",
                            PersonId = 4,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e8c0ee21-1707-4714-8d6f-3b70e8559d33",
                            TwoFactorEnabled = false,
                            UserName = "BlockManager1"
                        },
                        new
                        {
                            Id = "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2276b22-238d-41dc-8093-7833b547b3b9",
                            Email = "block.manager2@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BLOCK.MANAGER2@TEST.COM",
                            NormalizedUserName = "BLOCKMANAGER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0ItioypvBtT6icR2PNTB5m6PZCKydydokQRqVtsLTMiTzQ7JaI9PRiCFmpkWba+g==",
                            PersonId = 5,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f960618-9dc9-49f9-823e-af7fb8664c87",
                            TwoFactorEnabled = false,
                            UserName = "BlockManager2"
                        },
                        new
                        {
                            Id = "ffffffff-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3790f01f-2294-4cc4-8bc1-2cba31daa7de",
                            Email = "block.manager3@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BLOCK.MANAGER3@TEST.COM",
                            NormalizedUserName = "BLOCKMANAGER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEGzdhEPSmtiMtoJWd4LDDJlViAc5ZGjep9dwaSIxzDgWstp3HhjQSmDmqzEhM94VlA==",
                            PersonId = 6,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9452030b-8d9a-476b-9104-61f13fb6b2c5",
                            TwoFactorEnabled = false,
                            UserName = "BlockManager3"
                        },
                        new
                        {
                            Id = "10101010-1010-1010-1010-101010101010",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bb54d2f0-6595-4f93-8727-e5ab96e5fa20",
                            Email = "block.manager4@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BLOCK.MANAGER4@TEST.COM",
                            NormalizedUserName = "BLOCKMANAGER4",
                            PasswordHash = "AQAAAAIAAYagAAAAELJDymwUOf4oAw0/wk/URXYhrHgTE173uIrdkG0PB/AgUx47aghzGXCl4NZ6A+XeKw==",
                            PersonId = 7,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fbc82c86-d9cc-4f01-bfd4-5ffe9f6444a4",
                            TwoFactorEnabled = false,
                            UserName = "BlockManager4"
                        },
                        new
                        {
                            Id = "20202020-2020-2020-2020-202020202020",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff2ea36b-696e-49d3-9a32-6890f3595b8f",
                            Email = "block.manager5@test.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BLOCK.MANAGER5@TEST.COM",
                            NormalizedUserName = "BLOCKMANAGER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEH3TDYhc6YI3QQ9HVJ0Z4J8bSUTv9qeAYSqrDSyrGx5JFJVH/3twookhqJaDEgicSw==",
                            PersonId = 8,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57657e04-fb4d-4063-8be2-5c9f073a93fe",
                            TwoFactorEnabled = false,
                            UserName = "BlockManager5"
                        });
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.GovernmentInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GovernmentInstitutions");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.GovernmentInstitutionContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernmentInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernmentInstitutionId");

                    b.ToTable("GovernmentInstitutionContacts");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ProjectBlock", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "BlockId");

                    b.HasIndex("BlockId");

                    b.ToTable("ProjectBlock");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ProjectTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.ToTable("ProjectTeams");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialNeighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NeighborhoodManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NeighborhoodManagerId")
                        .IsUnique();

                    b.ToTable("ResidentialNeighborhoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "حي السلام",
                            NeighborhoodManagerId = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
                        });
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResidentialNeighborhoodId")
                        .HasColumnType("int");

                    b.Property<string>("UnitManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialNeighborhoodId");

                    b.HasIndex("UnitManagerId")
                        .IsUnique();

                    b.ToTable("ResidentialUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "الوحدة الأولى",
                            ResidentialNeighborhoodId = 1,
                            UnitManagerId = "cccccccc-cccc-cccc-cccc-cccccccccccc"
                        });
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.TeamRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "مدير المشروع"
                        },
                        new
                        {
                            Id = 2,
                            Name = "النائب"
                        },
                        new
                        {
                            Id = 3,
                            Name = "عضو"
                        });
                });

            modelBuilder.Entity("AdGroup", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Ad", null)
                        .WithMany()
                        .HasForeignKey("AdsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Block", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", "BlockManager")
                        .WithOne("ManagesBlock")
                        .HasForeignKey("OurProjectSmartNeiborhood.Entites.Block", "BlockManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNeighborhoodAPI.Entites.ResidentialUnit", "ResidentialUnit")
                        .WithMany("Blocks")
                        .HasForeignKey("ResidentialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockManager");

                    b.Navigation("ResidentialUnit");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ConflictCase", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Block", "Block")
                        .WithMany("ConflictCases")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.ConfilctType", "ConflictType")
                        .WithMany("Conflicts")
                        .HasForeignKey("ConflictTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.FamilyMember", "FirstParty")
                        .WithMany("FirstPartyConflictCases")
                        .HasForeignKey("FirstPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.FamilyMember", "SecondParty")
                        .WithMany("SecondPartyConflictCases")
                        .HasForeignKey("SecondPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("ConflictType");

                    b.Navigation("FirstParty");

                    b.Navigation("SecondParty");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Family", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Block", "Block")
                        .WithMany("Families")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.FamilyCatgory", "FamilyCatgory")
                        .WithMany("Families")
                        .HasForeignKey("FamilyCatgoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("FamilyCatgory");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.FamilyMember", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.MemberFamilyRole", "MemberFamilyRole")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("MemberFamilyRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Person", "Person")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("MemberFamilyRole");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Project", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.ProjectCatogory", "ProjectCatogory")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectCatogoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCatogory");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ProjectFamily", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Family", "Family")
                        .WithMany("ProjectFamilies")
                        .HasForeignKey("FamilyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Project", "Project")
                        .WithMany("ProjectFamilies")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.TeamMember", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Person", "Person")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartNeighborhoodAPI.Entites.TeamRole", "TeamRole")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.AppUser", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.GovernmentInstitutionContact", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.GovernmentInstitution", "GovernmentInstitution")
                        .WithMany("GovernmentInstitutionContacts")
                        .HasForeignKey("GovernmentInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovernmentInstitution");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ProjectBlock", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Block", "Block")
                        .WithMany("ProjectBlocks")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Project", "Project")
                        .WithMany("ProjectBlocks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ProjectTeam", b =>
                {
                    b.HasOne("OurProjectSmartNeiborhood.Entites.Project", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OurProjectSmartNeiborhood.Entites.Team", "Team")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialNeighborhood", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", "NeighborhoodManager")
                        .WithOne("ManagesNeighborhood")
                        .HasForeignKey("SmartNeighborhoodAPI.Entites.ResidentialNeighborhood", "NeighborhoodManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NeighborhoodManager");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialUnit", b =>
                {
                    b.HasOne("SmartNeighborhoodAPI.Entites.ResidentialNeighborhood", "ResidentialNeighborhood")
                        .WithMany("ResidentialUnits")
                        .HasForeignKey("ResidentialNeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNeighborhoodAPI.Entites.AppUser", "UnitManager")
                        .WithOne("ManagesUnit")
                        .HasForeignKey("SmartNeighborhoodAPI.Entites.ResidentialUnit", "UnitManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResidentialNeighborhood");

                    b.Navigation("UnitManager");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Block", b =>
                {
                    b.Navigation("ConflictCases");

                    b.Navigation("Families");

                    b.Navigation("ProjectBlocks");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ConfilctType", b =>
                {
                    b.Navigation("Conflicts");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Family", b =>
                {
                    b.Navigation("FamilyMembers");

                    b.Navigation("ProjectFamilies");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.FamilyCatgory", b =>
                {
                    b.Navigation("Families");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.FamilyMember", b =>
                {
                    b.Navigation("FirstPartyConflictCases");

                    b.Navigation("SecondPartyConflictCases");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.MemberFamilyRole", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Person", b =>
                {
                    b.Navigation("FamilyMembers");

                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Project", b =>
                {
                    b.Navigation("ProjectBlocks");

                    b.Navigation("ProjectFamilies");

                    b.Navigation("ProjectTeams");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.ProjectCatogory", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("OurProjectSmartNeiborhood.Entites.Team", b =>
                {
                    b.Navigation("ProjectTeams");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.AppUser", b =>
                {
                    b.Navigation("ManagesBlock");

                    b.Navigation("ManagesNeighborhood");

                    b.Navigation("ManagesUnit");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.GovernmentInstitution", b =>
                {
                    b.Navigation("GovernmentInstitutionContacts");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialNeighborhood", b =>
                {
                    b.Navigation("ResidentialUnits");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.ResidentialUnit", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("SmartNeighborhoodAPI.Entites.TeamRole", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
